#ifndef RENDERER_PIPELINE_H
#define RENDERER_PIPELINE_H

#include "core/types.h"

#ifdef __cplusplus
extern "C" {
#endif

// Pipeline stages for resource transitions and barriers
typedef enum PipelineStage {
    PIPELINE_STAGE_TOP_OF_PIPE = BIT(0),
    PIPELINE_STAGE_DRAW_INDIRECT = BIT(1),
    PIPELINE_STAGE_VERTEX_INPUT = BIT(2),
    PIPELINE_STAGE_VERTEX_SHADER = BIT(3),
    PIPELINE_STAGE_TESSELLATION_CONTROL = BIT(4),
    PIPELINE_STAGE_TESSELLATION_EVALUATION = BIT(5),
    PIPELINE_STAGE_GEOMETRY_SHADER = BIT(6),
    PIPELINE_STAGE_FRAGMENT_SHADER = BIT(7),
    PIPELINE_STAGE_EARLY_FRAGMENT_TESTS = BIT(8),
    PIPELINE_STAGE_LATE_FRAGMENT_TESTS = BIT(9),
    PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT = BIT(10),
    PIPELINE_STAGE_COMPUTE_SHADER = BIT(11),
    PIPELINE_STAGE_TRANSFER = BIT(12),
    PIPELINE_STAGE_BOTTOM_OF_PIPE = BIT(13),
    PIPELINE_STAGE_HOST = BIT(14),
    PIPELINE_STAGE_ALL_GRAPHICS = BIT(15),
    PIPELINE_STAGE_ALL_COMMANDS = BIT(16),
} PipelineStage;

typedef u32 PipelineStageFlags;

#ifdef __cplusplus
}
#endif

#endif // RENDERER_PIPELINE_H
