/**
 * @file thread_safety_verifier.h
 * @brief Comprehensive thread safety verification system for engine validation
 * 
 * This header defines a thread safety verification system that detects race conditions,
 * deadlocks, data races, and other concurrency issues in engine systems.
 * 
 * @author Minecraft v2 Engine Team
 * @date 2026-01-13
 */

#ifndef THREAD_SAFETY_VERIFIER_H
#define THREAD_SAFETY_VERIFIER_H

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

// ========================================
// Thread Safety Event Types
// ========================================

/**
 * @brief Types of thread safety events that can be detected
 */
typedef enum {
    THREAD_SAFETY_EVENT_LOCK_ACQUIRE,      // Mutex lock acquired
    THREAD_SAFETY_EVENT_LOCK_RELEASE,      // Mutex lock released
    THREAD_SAFETY_EVENT_LOCK_TRY,          // Mutex lock attempt
    THREAD_SAFETY_EVENT_LOCK_TIMEOUT,      // Mutex lock timeout
    THREAD_SAFETY_EVENT_READ_ACCESS,        // Memory read access
    THREAD_SAFETY_EVENT_WRITE_ACCESS,      // Memory write access
    THREAD_SAFETY_EVENT_ATOMIC_OPERATION,  // Atomic operation
    THREAD_SAFETY_EVENT_THREAD_CREATE,      // Thread creation
    THREAD_SAFETY_EVENT_THREAD_JOIN,        // Thread join
    THREAD_SAFETY_EVENT_THREAD_EXIT,        // Thread exit
    THREAD_SAFETY_EVENT_CONDITION_WAIT,     // Condition variable wait
    THREAD_SAFETY_EVENT_CONDITION_SIGNAL,   // Condition variable signal
    THREAD_SAFETY_EVENT_CONDITION_BROADCAST // Condition variable broadcast
} ThreadSafetyEventType;

/**
 * @brief Thread safety violation types
 */
typedef enum {
    THREAD_SAFETY_VIOLATION_NONE,           // No violation
    THREAD_SAFETY_VIOLATION_DATA_RACE,      // Data race detected
    THREAD_SAFETY_VIOLATION_DEADLOCK,        // Potential deadlock
    THREAD_SAFETY_VIOLATION_DOUBLE_LOCK,     // Double lock of same mutex
    THREAD_SAFETY_VIOLATION_UNLOCK_WITHOUT_LOCK, // Unlock without prior lock
    THREAD_SAFETY_VIOLATION_LOCK_ORDER_INVERSION, // Lock order inversion
    THREAD_SAFETY_VIOLATION_UNPROTECTED_ACCESS,  // Unprotected shared access
    THREAD_SAFETY_VIOLATION_ATOMICITY_VIOLATION, // Atomicity violation
    THREAD_SAFETY_VIOLATION_LIVELOCK,       // Livelock detected
    THREAD_SAFETY_VIOLATION_STARVATION,      // Thread starvation
    THREAD_SAFETY_VIOLATION_PRIORITY_INVERSION // Priority inversion
} ThreadSafetyViolationType;

// ========================================
// Data Structures
// ========================================

/**
 * @brief Thread safety event record
 * 
 * @param timestamp Event timestamp (nanoseconds)
 * @param thread_id Thread ID that generated the event
 * @param event_type Type of event
 * @param violation_type Type of violation (if any)
 * @param resource_id Resource identifier (mutex address, memory address, etc.)
 * @param resource_size Size of resource (for memory accesses)
 * @param stack_depth Stack trace depth
 * @param stack_trace Stack trace of event location
 * @param description Human-readable description
 * @param next Next event in linked list
 */
typedef struct ThreadSafetyEvent {
    uint64_t timestamp;
    pthread_t thread_id;
    ThreadSafetyEventType event_type;
    ThreadSafetyViolationType violation_type;
    void* resource_id;
    size_t resource_size;
    uint32_t stack_depth;
    void* stack_trace[16];
    char description[256];
    struct ThreadSafetyEvent* next;
} ThreadSafetyEvent;

/**
 * @brief Thread tracking information
 * 
 * @param thread_id Thread identifier
 * @param thread_name Thread name (if set)
 * @param creation_time Thread creation timestamp
 * @param last_activity Last activity timestamp
 * @param locks_held Number of locks currently held
 * @param lock_list List of locks held by thread
 * @param events_generated Total events generated by thread
 * @param violations_detected Total violations detected for thread
 * @param priority Thread priority
 * @param is_alive Thread is currently running
 */
typedef struct {
    pthread_t thread_id;
    char thread_name[64];
    uint64_t creation_time;
    uint64_t last_activity;
    uint32_t locks_held;
    void** lock_list;
    uint64_t events_generated;
    uint64_t violations_detected;
    int priority;
    bool is_alive;
} ThreadInfo;

/**
 * @brief Mutex tracking information
 * 
 * @param mutex_address Address of mutex
 * @param mutex_name Mutex name (if set)
 * @param creation_time Mutex creation timestamp
 * @param lock_count Total number of times locked
 * @param unlock_count Total number of times unlocked
 * @param current_owner Thread currently holding lock
 * @param lock_order_position Position in global lock order
 * @param max_hold_time Maximum time held (nanoseconds)
 * @param avg_hold_time Average time held (nanoseconds)
 * @param contention_count Number of contentions
 * @param is_recursive Whether mutex is recursive
 */
typedef struct {
    pthread_mutex_t* mutex_address;
    char mutex_name[64];
    uint64_t creation_time;
    uint64_t lock_count;
    uint64_t unlock_count;
    pthread_t current_owner;
    uint32_t lock_order_position;
    uint64_t max_hold_time;
    uint64_t avg_hold_time;
    uint64_t contention_count;
    bool is_recursive;
} MutexInfo;

/**
 * @brief Memory access tracking for data race detection
 * 
 * @param memory_address Memory address being accessed
 * @param access_size Size of memory access
 * @param last_read_thread Thread that last read this memory
 * @param last_read_time Timestamp of last read
 * @param last_write_thread Thread that last wrote this memory
 * @param last_write_time Timestamp of last write
 * @param access_pattern Access pattern flags
 * @param race_count Number of races detected at this address
 */
typedef struct {
    void* memory_address;
    size_t access_size;
    pthread_t last_read_thread;
    uint64_t last_read_time;
    pthread_t last_write_thread;
    uint64_t last_write_time;
    uint32_t access_pattern;
    uint32_t race_count;
} MemoryAccessInfo;

/**
 * @brief Thread safety verification configuration
 * 
 * @param enable_tracking Enable thread safety tracking
 * @param enable_data_race_detection Enable data race detection
 * @param enable_deadlock_detection Enable deadlock detection
 * @param enable_lock_order_analysis Enable lock order analysis
 * @param enable_performance_monitoring Enable performance monitoring
 * @param max_events Maximum events to track
 * @param max_threads Maximum threads to track
 * @param max_mutexes Maximum mutexes to track
 * @param memory_tracking_size Size of memory tracking table
 * @param violation_threshold Threshold for violation warnings
 * @param enable_stack_traces Enable stack trace capture
 * @param enable_real_time_analysis Enable real-time analysis
 */
typedef struct {
    bool enable_tracking;
    bool enable_data_race_detection;
    bool enable_deadlock_detection;
    bool enable_lock_order_analysis;
    bool enable_performance_monitoring;
    uint32_t max_events;
    uint32_t max_threads;
    uint32_t max_mutexes;
    uint32_t memory_tracking_size;
    uint32_t violation_threshold;
    bool enable_stack_traces;
    bool enable_real_time_analysis;
} ThreadSafetyConfig;

/**
 * @brief Thread safety verification statistics
 * 
 * @param total_events Total events tracked
 * @param violations_detected Total violations detected
 * @param data_races_detected Data races detected
 * @param deadlocks_detected Deadlocks detected
 * @param lock_inversions_detected Lock order inversions detected
 * @param threads_tracked Total threads tracked
 * @param mutexes_tracked Total mutexes tracked
 * @param memory_accesses_tracked Total memory accesses tracked
 * @param analysis_time_ns Total time spent in analysis
 * @param overhead_percentage Performance overhead percentage
 */
typedef struct {
    uint64_t total_events;
    uint64_t violations_detected;
    uint64_t data_races_detected;
    uint64_t deadlocks_detected;
    uint64_t lock_inversions_detected;
    uint64_t threads_tracked;
    uint64_t mutexes_tracked;
    uint64_t memory_accesses_tracked;
    uint64_t analysis_time_ns;
    double overhead_percentage;
} ThreadSafetyStats;

// ========================================
// Core Functions
// ========================================

/**
 * @brief Initialize thread safety verification system
 * 
 * Sets up the thread safety verification system with the specified configuration.
 * Must be called before any thread safety functions are used.
 * 
 * @param config Configuration for thread safety verification (NULL for defaults)
 * @return true if initialization successful, false otherwise
 */
bool thread_safety_verifier_init(const ThreadSafetyConfig* config);

/**
 * @brief Shutdown thread safety verification system
 * 
 * Cleans up the thread safety verification system and generates a final report.
 * Should be called when the application is shutting down.
 * 
 * @param report_file File to write final report to (NULL for stdout)
 * @return true if shutdown successful, false otherwise
 */
bool thread_safety_verifier_shutdown(const char* report_file);

/**
 * @brief Record a thread safety event
 * 
 * Records a thread safety event for analysis. This function is typically
 * called by instrumented code or wrapper functions.
 * 
 * @param event_type Type of event
 * @param resource_id Resource identifier (mutex address, memory address, etc.)
 * @param resource_size Size of resource (for memory accesses)
 * @param description Human-readable description
 * @return true if event recorded successfully, false otherwise
 */
bool thread_safety_verifier_record_event(ThreadSafetyEventType event_type,
                                        void* resource_id,
                                        size_t resource_size,
                                        const char* description);

/**
 * @brief Analyze recorded events for violations
 * 
 * Analyzes all recorded events to detect thread safety violations.
 * This can be called periodically or on demand.
 * 
 * @return Number of violations detected
 */
uint32_t thread_safety_verifier_analyze(void);

/**
 * @brief Check for potential deadlocks
 * 
 * Analyzes current lock state to detect potential deadlocks.
 * 
 * @return Number of potential deadlocks detected
 */
uint32_t thread_safety_verifier_check_deadlocks(void);

/**
 * @brief Check for data races
 * 
 * Analyzes memory access patterns to detect data races.
 * 
 * @return Number of data races detected
 */
uint32_t thread_safety_verifier_check_data_races(void);

// ========================================
// Mutex Wrapper Functions
// ========================================

/**
 * @brief Wrapper for pthread_mutex_lock with tracking
 * 
 * Wraps pthread_mutex_lock to add thread safety tracking.
 * 
 * @param mutex Mutex to lock
 * @param mutex_name Name of mutex (optional)
 * @return Same return value as pthread_mutex_lock
 */
int thread_safe_mutex_lock(pthread_mutex_t* mutex, const char* mutex_name);

/**
 * @brief Wrapper for pthread_mutex_unlock with tracking
 * 
 * Wraps pthread_mutex_unlock to add thread safety tracking.
 * 
 * @param mutex Mutex to unlock
 * @return Same return value as pthread_mutex_unlock
 */
int thread_safe_mutex_unlock(pthread_mutex_t* mutex);

/**
 * @brief Wrapper for pthread_mutex_trylock with tracking
 * 
 * Wraps pthread_mutex_trylock to add thread safety tracking.
 * 
 * @param mutex Mutex to try to lock
 * @return Same return value as pthread_mutex_trylock
 */
int thread_safe_mutex_trylock(pthread_mutex_t* mutex);

/**
 * @brief Wrapper for pthread_mutex_timedlock with tracking
 * 
 * Wraps pthread_mutex_timedlock to add thread safety tracking.
 * 
 * @param mutex Mutex to lock
 * @param timeout Timeout specification
 * @return Same return value as pthread_mutex_timedlock
 */
int thread_safe_mutex_timedlock(pthread_mutex_t* mutex, const struct timespec* timeout);

// ========================================
// Memory Access Tracking
// ========================================

/**
 * @brief Track a memory read access
 * 
 * Records a memory read access for data race detection.
 * 
 * @param address Memory address being read
 * @param size Size of memory being read
 * @param description Description of access (optional)
 */
void thread_safety_track_memory_read(void* address, size_t size, const char* description);

/**
 * @brief Track a memory write access
 * 
 * Records a memory write access for data race detection.
 * 
 * @param address Memory address being written
 * @param size Size of memory being written
 * @param description Description of access (optional)
 */
void thread_safety_track_memory_write(void* address, size_t size, const char* description);

/**
 * @brief Track an atomic memory operation
 * 
 * Records an atomic memory operation.
 * 
 * @param address Memory address being accessed atomically
 * @param size Size of atomic operation
 * @param description Description of operation (optional)
 */
void thread_safety_track_atomic_operation(void* address, size_t size, const char* description);

// ========================================
// Statistics and Reporting
// ========================================

/**
 * @brief Get current thread safety statistics
 * 
 * Returns comprehensive statistics about thread safety monitoring.
 * 
 * @return Current statistics structure
 */
ThreadSafetyStats thread_safety_verifier_get_stats(void);

/**
 * @brief Generate thread safety violation report
 * 
 * Generates a detailed report of all thread safety violations detected.
 * 
 * @param violations Array to store violation events
 * @param max_violations Maximum number of violations to store
 * @param violation_type Filter by violation type (VIOLATION_NONE for all)
 * @return Number of violations stored
 */
uint32_t thread_safety_verifier_get_violations(ThreadSafetyEvent* violations,
                                               uint32_t max_violations,
                                               ThreadSafetyViolationType violation_type);

/**
 * @brief Print thread safety statistics
 * 
 * Prints current thread safety statistics to the specified output.
 * 
 * @param output_file File to print to (NULL for stdout)
 * @param verbose Enable verbose output with detailed information
 */
void thread_safety_verifier_print_stats(const char* output_file, bool verbose);

/**
 * @brief Print thread safety violation report
 * 
 * Prints a detailed thread safety violation report to the specified output.
 * 
 * @param output_file File to print to (NULL for stdout)
 * @param include_stack_traces Include stack traces in output
 * @param sort_by_timestamp Sort violations by timestamp
 */
void thread_safety_verifier_print_violations(const char* output_file,
                                            bool include_stack_traces,
                                            bool sort_by_timestamp);

/**
 * @brief Export thread safety data for external analysis
 * 
 * Exports all thread safety data in a format suitable for external analysis tools.
 * 
 * @param export_file File to export data to
 * @param format Export format ("json", "csv", "xml")
 * @return true if export successful, false otherwise
 */
bool thread_safety_verifier_export_data(const char* export_file, const char* format);

// ========================================
// Advanced Features
// ========================================

/**
 * @brief Set thread safety violation threshold
 * 
 * Sets thresholds for when to generate warnings about violations.
 * 
 * @param violation_threshold Number of violations before warning
 * @param time_threshold_seconds Time window for violation counting
 */
void thread_safety_verifier_set_threshold(uint32_t violation_threshold,
                                          uint32_t time_threshold_seconds);

/**
 * @brief Enable/disable real-time analysis
 * 
 * Enables or disables real-time analysis of thread safety events.
 * 
 * @param enable Enable real-time analysis
 */
void thread_safety_verifier_set_real_time_analysis(bool enable);

/**
 * @brief Get thread information
 * 
 * Retrieves information about a specific thread.
 * 
 * @param thread_id Thread ID to look up
 * @return Thread information structure or NULL if not found
 */
const ThreadInfo* thread_safety_verifier_get_thread_info(pthread_t thread_id);

/**
 * @brief Get mutex information
 * 
 * Retrieves information about a specific mutex.
 * 
 * @param mutex Mutex to look up
 * @return Mutex information structure or NULL if not found
 */
const MutexInfo* thread_safety_verifier_get_mutex_info(pthread_mutex_t* mutex);

/**
 * @brief Get memory access information
 * 
 * Retrieves information about memory accesses at a specific address.
 * 
 * @param address Memory address to look up
 * @return Memory access information or NULL if not found
 */
const MemoryAccessInfo* thread_safety_verifier_get_memory_info(void* address);

/**
 * @brief Clear all thread safety data
 * 
 * Clears all tracked thread safety data while keeping the system active.
 * Useful for testing different phases of application execution.
 */
void thread_safety_verifier_clear_all(void);

/**
 * @brief Validate lock order consistency
 * 
 * Validates that lock acquisition order is consistent across all threads
 * to prevent lock order inversions.
 * 
 * @return Number of lock order violations detected
 */
uint32_t thread_safety_verifier_validate_lock_order(void);

#ifdef __cplusplus
}
#endif

#endif // THREAD_SAFETY_VERIFIER_H
