#include "mesh.h"
#include <core/memory.h>
#include <core/logger.h>
#include <string.h>
#include <math.h>
#include <float.h> // For FLT_MAX

// ----------------------------------------------------------------------------
// Lifecycle
// ----------------------------------------------------------------------------

mesh_t* mesh_create(const char* name) {
    mesh_t* mesh = (mesh_t*)MALLOC_GEOMETRY(sizeof(mesh_t));
    memset(mesh, 0, sizeof(mesh_t));
    
    if (name) {
        strncpy(mesh->name, name, 63);
        mesh->name[63] = '\0';
    } else {
        strncpy(mesh->name, "unnamed_mesh", 63);
    }
    
    // Default ID (Should be generated by a resource manager)
    static u32 geometry_id_counter = 0;
    mesh->id = ++geometry_id_counter;
    
    mesh->ref_count = 1;
    mesh->flags = MESH_FLAG_NONE;

    return mesh;
}

void mesh_destroy(mesh_t* mesh) {
    if (!mesh) return;
    
    mesh->ref_count--;
    if (mesh->ref_count > 0) return;

    // TODO: Release GPU resources
    // if (mesh->vertex_buffer_handle != 0) gpu_free_buffer(mesh->vertex_buffer_handle);
    // if (mesh->index_buffer_handle != 0) gpu_free_buffer(mesh->index_buffer_handle);

    if (mesh->vertices) {
        FREE(mesh->vertices);
    }

    if (mesh->indices) {
        FREE(mesh->indices);
    }

    if (mesh->submeshes) {
        FREE(mesh->submeshes);
    }

    FREE(mesh);
}

// ----------------------------------------------------------------------------
// Buffer Management
// ----------------------------------------------------------------------------

void mesh_allocate_buffers(mesh_t* mesh, u32 vertex_count, u32 index_count) {
    if (!mesh) return;

    if (mesh->vertices) {
        FREE(mesh->vertices);
    }
    
    if (mesh->indices) {
        FREE(mesh->indices);
    }

    mesh->vertex_capacity = vertex_count;
    mesh->index_capacity = index_count;
    mesh->vertex_count = 0;
    mesh->index_count = 0;

    if (vertex_count > 0) {
        mesh->vertices = (vertex_t*)MALLOC_GEOMETRY(sizeof(vertex_t) * vertex_count);
    }
    
    if (index_count > 0) {
        mesh->indices = (u32*)MALLOC_GEOMETRY(sizeof(u32) * index_count);
    }
}

void mesh_set_vertices(mesh_t* mesh, const vertex_t* vertices, u32 count, u32 offset) {
    if (!mesh || !vertices) return;
    if (offset + count > mesh->vertex_capacity) {
        LOG_ERROR("mesh_set_vertices: Out of bounds. Capacity: %d, Request: %d", mesh->vertex_capacity, offset + count);
        return;
    }

    memcpy(mesh->vertices + offset, vertices, sizeof(vertex_t) * count);
    if (offset + count > mesh->vertex_count) {
        mesh->vertex_count = offset + count;
    }
    
    mesh->flags |= MESH_FLAG_DYNAMIC; // Mark as dirty/dynamic if updated
}

void mesh_set_indices(mesh_t* mesh, const u32* indices, u32 count, u32 offset) {
    if (!mesh || !indices) return;
    if (offset + count > mesh->index_capacity) {
        LOG_ERROR("mesh_set_indices: Out of bounds. Capacity: %d, Request: %d", mesh->index_capacity, offset + count);
        return;
    }

    memcpy(mesh->indices + offset, indices, sizeof(u32) * count);
    if (offset + count > mesh->index_count) {
        mesh->index_count = offset + count;
    }
}

// ----------------------------------------------------------------------------
// Submesh Management
// ----------------------------------------------------------------------------

void mesh_add_submesh(mesh_t* mesh, submesh_t submesh) {
    if (!mesh) return;
    
    // Very simple dynamic array for submeshes
    u32 new_count = mesh->submesh_count + 1;
    submesh_t* new_submeshes = (submesh_t*)MALLOC_GEOMETRY(sizeof(submesh_t) * new_count);
    
    if (mesh->submeshes) {
        memcpy(new_submeshes, mesh->submeshes, sizeof(submesh_t) * mesh->submesh_count);
        FREE(mesh->submeshes);
    }
    
    new_submeshes[mesh->submesh_count] = submesh;
    mesh->submeshes = new_submeshes;
    mesh->submesh_count = new_count;
}

void mesh_clear_submeshes(mesh_t* mesh) {
    if (!mesh) return;
    if (mesh->submeshes) {
        FREE(mesh->submeshes);
    }
    mesh->submeshes = 0;
    mesh->submesh_count = 0;
}

void mesh_set_material(mesh_t* mesh, u32 slot, u32 material_id) {
    if (!mesh) return;
    if (slot >= MESH_MAX_MATERIALS) {
        LOG_ERROR("mesh_set_material: Slot %d out of bounds (Max %d)", slot, MESH_MAX_MATERIALS);
        return;
    }
    mesh->material_ids[slot] = material_id;
    if (slot >= mesh->material_count) {
        mesh->material_count = slot + 1;
    }
}

// ----------------------------------------------------------------------------
// Operations
// ----------------------------------------------------------------------------

void mesh_calculate_bounds(mesh_t* mesh) {
    if (!mesh || mesh->vertex_count == 0) {
        memset(&mesh->bounds, 0, sizeof(mesh_bounds_t));
        return;
    }

    Vec3 min = {FLT_MAX, FLT_MAX, FLT_MAX};
    Vec3 max = {-FLT_MAX, -FLT_MAX, -FLT_MAX};

    for (u32 i = 0; i < mesh->vertex_count; ++i) {
        Vec3 p = mesh->vertices[i].position;
        if (p.x < min.x) min.x = p.x;
        if (p.y < min.y) min.y = p.y;
        if (p.z < min.z) min.z = p.z;
        
        if (p.x > max.x) max.x = p.x;
        if (p.y > max.y) max.y = p.y;
        if (p.z > max.z) max.z = p.z;
    }

    mesh->bounds.min = min;
    mesh->bounds.max = max;

    // Calculate center and radius
    Vec3 center = vec3_add(min, max);
    mesh->bounds.sphere_center = vec3_mul(center, 0.5f);
    
    f32 max_dist_sq = 0.0f;
    for (u32 i = 0; i < mesh->vertex_count; ++i) {
        Vec3 p = mesh->vertices[i].position;
        f32 dist_sq = vec3_distance_sq(p, mesh->bounds.sphere_center);
        if (dist_sq > max_dist_sq) {
            max_dist_sq = dist_sq;
        }
    }
    mesh->bounds.sphere_radius = sqrtf(max_dist_sq);
}

// ----------------------------------------------------------------------------
// Stubbed Functions (To Impl)
// ----------------------------------------------------------------------------

void mesh_calculate_normals(mesh_t* mesh) {
    if (!mesh || !mesh->vertices || !mesh->indices) return;

    // Reset normals
    for (u32 i = 0; i < mesh->vertex_count; ++i) {
        mesh->vertices[i].normal = (Vec3){0, 0, 0};
    }

    // Iterate triangles
    for (u32 i = 0; i < mesh->index_count; i += 3) {
        u32 i0 = mesh->indices[i];
        u32 i1 = mesh->indices[i + 1];
        u32 i2 = mesh->indices[i + 2];

        Vec3 v0 = mesh->vertices[i0].position;
        Vec3 v1 = mesh->vertices[i1].position;
        Vec3 v2 = mesh->vertices[i2].position;

        Vec3 edge1 = vec3_sub(v1, v0);
        Vec3 edge2 = vec3_sub(v2, v0);

        // Cross product is area weighted, so don't normalize yet
        Vec3 normal = vec3_cross(edge1, edge2);

        // Accumulate
        mesh->vertices[i0].normal = vec3_add(mesh->vertices[i0].normal, normal);
        mesh->vertices[i1].normal = vec3_add(mesh->vertices[i1].normal, normal);
        mesh->vertices[i2].normal = vec3_add(mesh->vertices[i2].normal, normal);
    }

    // Normalize result
    for (u32 i = 0; i < mesh->vertex_count; ++i) {
        mesh->vertices[i].normal = vec3_normalize(mesh->vertices[i].normal);
    }
}

void mesh_calculate_tangents(mesh_t* mesh) {
    // TODO: Implement MikkTSpace or simple tangent gen
}

bool mesh_upload(mesh_t* mesh) {
    // TODO: Call into GPU backend
    // mesh->is_uploaded = true; 
    return true; 
}

void mesh_unload(mesh_t* mesh) {
    // TODO: Call into GPU backend
    // mesh->is_uploaded = false;
}

void mesh_print_stats(const mesh_t* mesh) {
    if (!mesh) return;
    LOG_INFO("Mesh Stats - Name: %s, ID: %d", mesh->name, mesh->id);
    LOG_INFO("  Vertices: %d, Indices: %d", mesh->vertex_count, mesh->index_count);
    LOG_INFO("  Submeshes: %d, Materials: %d", mesh->submesh_count, mesh->material_count);
    LOG_INFO("  Bounds Center: (%.2f, %.2f, %.2f) Radius: %.2f", 
        mesh->bounds.sphere_center.x, mesh->bounds.sphere_center.y, mesh->bounds.sphere_center.z, 
        mesh->bounds.sphere_radius);
}

bool mesh_validate(const mesh_t* mesh) {
    if (!mesh) return false;
    if (mesh->vertex_count > 0 && !mesh->vertices) return false;
    if (mesh->index_count > 0 && !mesh->indices) return false;
    return true;
}
