#ifndef PHYSICS_COMPUTE_SHADERS_H
#define PHYSICS_COMPUTE_SHADERS_H

/* ============================================================================
 * NAVIER-STOKES GPU COMPUTE SHADER (GLSL 4.3+)
 * ============================================================================
 */

static const char* NAVIER_STOKES_COMPUTE_SHADER =
"#version 430 core\n"
"\n"
"layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;\n"
"\n"
"layout(std430, binding = 0) buffer VelocityX { float vel_x[]; };\n"
"layout(std430, binding = 1) buffer VelocityY { float vel_y[]; };\n"
"layout(std430, binding = 2) buffer VelocityZ { float vel_z[]; };\n"
"layout(std430, binding = 3) buffer Density { float density[]; };\n"
"layout(std430, binding = 4) buffer Pressure { float pressure[]; };\n"
"\n"
"uniform int grid_size;\n"
"uniform float dt;\n"
"uniform float viscosity;\n"
"\n"
"int coord_to_index(ivec3 coord) {\n"
"    return coord.z * grid_size * grid_size + coord.y * grid_size + coord.x;\n"
"}\n"
"\n"
"float sample_vel_x(ivec3 coord) {\n"
"    if (coord.x < 0 || coord.x >= grid_size || \n"
"        coord.y < 0 || coord.y >= grid_size || \n"
"        coord.z < 0 || coord.z >= grid_size) return 0.0;\n"
"    return vel_x[coord_to_index(coord)];\n"
"}\n"
"\n"
"// MacCormack advection step\n"
"void main() {\n"
"    ivec3 coord = ivec3(gl_GlobalInvocationID.xyz);\n"
"    if (coord.x >= grid_size || coord.y >= grid_size || coord.z >= grid_size) return;\n"
"    \n"
"    int idx = coord_to_index(coord);\n"
"    \n"
"    // Forward trace\n"
"    vec3 vel = vec3(vel_x[idx], vel_y[idx], vel_z[idx]);\n"
"    vec3 back_pos = vec3(coord) - vel * dt;\n"
"    \n"
"    // Sample at back position (trilinear interpolation)\n"
"    ivec3 cell = ivec3(floor(back_pos));\n"
"    vec3 frac = fract(back_pos);\n"
"    \n"
"    // Advect density\n"
"    float d000 = density[coord_to_index(cell + ivec3(0,0,0))];\n"
"    float d001 = density[coord_to_index(cell + ivec3(0,0,1))];\n"
"    float d010 = density[coord_to_index(cell + ivec3(0,1,0))];\n"
"    float d011 = density[coord_to_index(cell + ivec3(0,1,1))];\n"
"    float d100 = density[coord_to_index(cell + ivec3(1,0,0))];\n"
"    float d101 = density[coord_to_index(cell + ivec3(1,0,1))];\n"
"    float d110 = density[coord_to_index(cell + ivec3(1,1,0))];\n"
"    float d111 = density[coord_to_index(cell + ivec3(1,1,1))];\n"
"    \n"
"    float advected = mix(\n"
"        mix(mix(d000, d100, frac.x), mix(d010, d110, frac.x), frac.y),\n"
"        mix(mix(d001, d101, frac.x), mix(d011, d111, frac.x), frac.y),\n"
"        frac.z\n"
"    );\n"
"    \n"
"    density[idx] = advected;\n"
"}\n";

/* ============================================================================
 * FLIP SOLVER GPU COMPUTE SHADER
 * ============================================================================
 */

static const char* FLIP_P2G_SHADER =
"#version 430 core\n"
"\n"
"layout(local_size_x = 256) in;\n"
"\n"
"struct Particle {\n"
"    vec3 position;\n"
"    vec3 velocity;\n"
"};\n"
"\n"
"layout(std430, binding = 0) buffer Particles { Particle particles[]; };\n"
"layout(std430, binding = 1) buffer GridVelX { float grid_u[]; };\n"
"layout(std430, binding = 2) buffer GridVelY { float grid_v[]; };\n"
"layout(std430, binding = 3) buffer GridVelZ { float grid_w[]; };\n"
"\n"
"uniform int particle_count;\n"
"uniform int grid_size;\n"
"uniform float cell_size;\n"
"\n"
"void main() {\n"
"    uint pid = gl_GlobalInvocationID.x;\n"
"    if (pid >= particle_count) return;\n"
"    \n"
"    Particle p = particles[pid];\n"
"    \n"
"    // Map particle to grid\n"
"    vec3 grid_pos = p.position / cell_size;\n"
"    ivec3 cell = ivec3(floor(grid_pos));\n"
"    vec3 frac = fract(grid_pos);\n"
"    \n"
"    // Trilinear weights\n"
"    float wx[2] = { 1.0 - frac.x, frac.x };\n"
"    float wy[2] = { 1.0 - frac.y, frac.y };\n"
"    float wz[2] = { 1.0 - frac.z, frac.z };\n"
"    \n"
"    // Transfer momentum to grid (P2G)\n"
"    for (int i = 0; i < 2; i++) {\n"
"        for (int j = 0; j < 2; j++) {\n"
"            for (int k = 0; k < 2; k++) {\n"
"                ivec3 grid_cell = cell + ivec3(i, j, k);\n"
"                int idx = grid_cell.z * grid_size * grid_size + grid_cell.y * grid_size + grid_cell.x;\n"
"                float weight = wx[i] * wy[j] * wz[k];\n"
"                \n"
"                atomicAdd(grid_u[idx], p.velocity.x * weight);\n"
"                atomicAdd(grid_v[idx], p.velocity.y * weight);\n"
"                atomicAdd(grid_w[idx], p.velocity.z * weight);\n"
"            }\n"
"        }\n"
"    }\n"
"}\n";

/* ============================================================================
 * SPH GPU COMPUTE SHADER
 * ============================================================================
 */

static const char* SPH_DENSITY_SHADER =
"#version 430 core\n"
"\n"
"layout(local_size_x = 256) in;\n"
"\n"
"struct SPHParticle {\n"
"    vec3 position;\n"
"    vec3 velocity;\n"
"    float density;\n"
"    float pressure;\n"
"};\n"
"\n"
"layout(std430, binding = 0) buffer Particles { SPHParticle particles[]; };\n"
"\n"
"uniform int particle_count;\n"
"uniform float kernel_radius;\n"
"uniform float rest_density;\n"
"uniform float stiffness;\n"
"\n"
"float poly6_kernel(float r, float h) {\n"
"    if (r >= h) return 0.0;\n"
"    float h2_r2 = h*h - r*r;\n"
"    return (315.0 / (64.0 * 3.14159 * pow(h, 9.0))) * h2_r2 * h2_r2 * h2_r2;\n"
"}\n"
"\n"
"void main() {\n"
"    uint pid = gl_GlobalInvocationID.x;\n"
"    if (pid >= particle_count) return;\n"
"    \n"
"    SPHParticle p = particles[pid];\n"
"    float density_sum = 0.0;\n"
"    \n"
"    // Compute density\n"
"    for (int i = 0; i < particle_count; i++) {\n"
"        vec3 r_vec = particles[i].position - p.position;\n"
"        float r = length(r_vec);\n"
"        density_sum += poly6_kernel(r, kernel_radius);\n"
"    }\n"
"    \n"
"    particles[pid].density = density_sum;\n"
"    particles[pid].pressure = stiffness * (density_sum - rest_density);\n"
"}\n";

/* ============================================================================
 * PARTICLE SYSTEM GPU SHADER
 * ============================================================================
 */

static const char* PARTICLE_UPDATE_SHADER =
"#version 430 core\n"
"\n"
"layout(local_size_x = 256) in;\n"
"\n"
"struct Particle {\n"
"    vec3 position;\n"
"    vec3 velocity;\n"
"    float lifetime;\n"
"    float size;\n"
"};\n"
"\n"
"layout(std430, binding = 0) buffer ParticleBuffer { Particle particles[]; };\n"
"\n"
"uniform int particle_count;\n"
"uniform float dt;\n"
"uniform vec3 gravity;\n"
"\n"
"void main() {\n"
"    uint pid = gl_GlobalInvocationID.x;\n"
"    if (pid >= particle_count) return;\n"
"    \n"
"    Particle p = particles[pid];\n"
"    \n"
"    // Skip dead particles\n"
"    if (p.lifetime <= 0.0) return;\n"
"    \n"
"    // Update lifetime\n"
"    p.lifetime -= dt;\n"
"    \n"
"    // Apply gravity\n"
"    p.velocity += gravity * dt;\n"
"    \n"
"    // Update position\n"
"    p.position += p.velocity * dt;\n"
"    \n"
"    // Write back\n"
"    particles[pid] = p;\n"
"}\n";

/* ============================================================================
 * SHALLOW WATER GPU SHADER
 * ============================================================================
 */

static const char* SHALLOW_WATER_SHADER =
"#version 430 core\n"
"\n"
"layout(local_size_x = 16, local_size_y = 16) in;\n"
"\n"
"layout(std430, binding = 0) buffer Height { float height[]; };\n"
"layout(std430, binding = 1) buffer VelX { float vel_x[]; };\n"
"layout(std430, binding = 2) buffer VelZ { float vel_z[]; };\n"
"\n"
"uniform int width;\n"
"uniform int depth;\n"
"uniform float dt;\n"
"uniform float wave_speed;\n"
"\n"
"int coord(int x, int z) {\n"
"    return z * width + x;\n"
"}\n"
"\n"
"void main() {\n"
"    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);\n"
"    if (pos.x >= width || pos.y >= depth) return;\n"
"    \n"
"    int idx = coord(pos.x, pos.y);\n"
"    \n"
"    // Shallow water equations\n"
"    float h = height[idx];\n"
"    float vx = vel_x[idx];\n"
"    float vz = vel_z[idx];\n"
"    \n"
"    // Gradient\n"
"    float dh_dx = (height[coord(min(pos.x+1, width-1), pos.y)] - \n"
"                   height[coord(max(pos.x-1, 0), pos.y)]) * 0.5;\n"
"    float dh_dz = (height[coord(pos.x, min(pos.y+1, depth-1))] - \n"
"                   height[coord(pos.x, max(pos.y-1, 0))]) * 0.5;\n"
"    \n"
"    // Update velocities\n"
"    vx -= wave_speed * dh_dx * dt;\n"
"    vz -= wave_speed * dh_dz * dt;\n"
"    \n"
"    // Update height\n"
"    float div = (vel_x[coord(min(pos.x+1, width-1), pos.y)] - \n"
"                 vel_x[coord(max(pos.x-1, 0), pos.y)]) * 0.5 +\n"
"                (vel_z[coord(pos.x, min(pos.y+1, depth-1))] - \n"
"                 vel_z[coord(pos.x, max(pos.y-1, 0))]) * 0.5;\n"
"    \n"
"    height[idx] = h - div * dt;\n"
"    vel_x[idx] = vx * 0.99; // Damping\n"
"    vel_z[idx] = vz * 0.99;\n"
"}\n";

/* ============================================================================
 * GPU BROADPHASE (SPATIAL HASHING)
 * ============================================================================
 */

static const char* GPU_BROADPHASE_SHADER =
"#version 430 core\n"
"\n"
"layout(local_size_x = 256) in;\n"
"\n"
"struct AABB {\n"
"    vec3 min_pos;\n"
"    vec3 max_pos;\n"
"    uint body_id;\n"
"};\n"
"\n"
"layout(std430, binding = 0) buffer AABBs { AABB boxes[]; };\n"
"layout(std430, binding = 1) buffer HashTable { uint hash_table[]; };\n"
"layout(std430, binding = 2) buffer Pairs { uvec2 pairs[]; };\n"
"\n"
"uniform int box_count;\n"
"uniform int hash_size;\n"
"uniform float cell_size;\n"
"\n"
"uint spatial_hash(vec3 pos) {\n"
"    ivec3 cell = ivec3(floor(pos / cell_size));\n"
"    return ((cell.x * 73856093) ^ (cell.y * 19349663) ^ (cell.z * 83492791)) % hash_size;\n"
"}\n"
"\n"
"void main() {\n"
"    uint bid = gl_GlobalInvocationID.x;\n"
"    if (bid >= box_count) return;\n"
"    \n"
"    AABB box = boxes[bid];\n"
"    \n"
"    // Hash AABB center\n"
"    vec3 center = (box.min_pos + box.max_pos) * 0.5;\n"
"    uint hash = spatial_hash(center);\n"
"    \n"
"    // Insert into hash table (simplified - needs atomic operations)\n"
"    atomicExch(hash_table[hash], bid);\n"
"}\n";

#endif // PHYSICS_COMPUTE_SHADERS_H
