# CMake generated Testfile for 
# Source directory: /Users/benjaminrussell/Desktop/Minecraft v2
# Build directory: /Users/benjaminrussell/Desktop/Minecraft v2/build_phase1
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_render_graph]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_render_graph")
set_tests_properties([=[test_render_graph]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;709;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_simd_math]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_simd_math")
set_tests_properties([=[test_simd_math]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;712;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_material_system]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_material_system")
set_tests_properties([=[test_material_system]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;715;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_post_processing]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_post_processing")
set_tests_properties([=[test_post_processing]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;718;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_ai_command_processor]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_ai_command_processor")
set_tests_properties([=[test_ai_command_processor]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;723;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_content_manager]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_content_manager")
set_tests_properties([=[test_content_manager]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;724;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_perception_system]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_perception_system")
set_tests_properties([=[test_perception_system]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;725;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_utility_ai]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_utility_ai")
set_tests_properties([=[test_utility_ai]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;726;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_goap_enhanced]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_goap_enhanced")
set_tests_properties([=[test_goap_enhanced]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;727;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_memory_system]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_memory_system")
set_tests_properties([=[test_memory_system]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;728;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_audio_system]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_audio_system")
set_tests_properties([=[test_audio_system]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;733;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_audio_manager]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_audio_manager")
set_tests_properties([=[test_audio_manager]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;734;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_logger]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_logger")
set_tests_properties([=[test_logger]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;739;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_memory]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_memory")
set_tests_properties([=[test_memory]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;740;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_string_utils]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_string_utils")
set_tests_properties([=[test_string_utils]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;741;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_cache]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_cache")
set_tests_properties([=[test_cache]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;742;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_hashmap]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_hashmap")
set_tests_properties([=[test_hashmap]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;705;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;743;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
subdirs("src/engine/test")
