# CMake generated Testfile for 
# Source directory: /Users/benjaminrussell/Desktop/Minecraft v2
# Build directory: /Users/benjaminrussell/Desktop/Minecraft v2/build_phase1
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[Phase1_BuildSystem]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_phase1_build_system")
set_tests_properties([=[Phase1_BuildSystem]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;679;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_render_graph]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_render_graph")
set_tests_properties([=[test_render_graph]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;698;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_simd_math]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_simd_math")
set_tests_properties([=[test_simd_math]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;701;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_soa_container]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_soa_container")
set_tests_properties([=[test_soa_container]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;704;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_physics_integration]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_physics_integration")
set_tests_properties([=[test_physics_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;707;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_aabb_tree]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_aabb_tree")
set_tests_properties([=[test_aabb_tree]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;710;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_collision_gjk_epa]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_collision_gjk_epa")
set_tests_properties([=[test_collision_gjk_epa]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;713;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_material_system]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_material_system")
set_tests_properties([=[test_material_system]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;716;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_post_processing]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_post_processing")
set_tests_properties([=[test_post_processing]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;719;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_ai_command_processor]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_ai_command_processor")
set_tests_properties([=[test_ai_command_processor]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;724;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_perception_system]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_perception_system")
set_tests_properties([=[test_perception_system]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;726;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_utility_ai]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_utility_ai")
set_tests_properties([=[test_utility_ai]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;727;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_goap_enhanced]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_goap_enhanced")
set_tests_properties([=[test_goap_enhanced]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;728;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_memory_system]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_memory_system")
set_tests_properties([=[test_memory_system]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;729;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_audio_system]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_audio_system")
set_tests_properties([=[test_audio_system]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;734;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_audio_manager]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_audio_manager")
set_tests_properties([=[test_audio_manager]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;735;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_logger]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_logger")
set_tests_properties([=[test_logger]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;740;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_memory]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_memory")
set_tests_properties([=[test_memory]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;741;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_string_utils]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_string_utils")
set_tests_properties([=[test_string_utils]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;742;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_cache]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_cache")
set_tests_properties([=[test_cache]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;743;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_hashmap]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_hashmap")
set_tests_properties([=[test_hashmap]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;744;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_ecs]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_ecs")
set_tests_properties([=[test_ecs]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;749;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_vec3]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_vec3")
set_tests_properties([=[test_vec3]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;754;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_mat4]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_mat4")
set_tests_properties([=[test_mat4]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;755;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_quat]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_quat")
set_tests_properties([=[test_quat]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;756;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_protocol1_energy]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_protocol1_energy")
set_tests_properties([=[test_protocol1_energy]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;762;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_protocol2_stacking]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_protocol2_stacking")
set_tests_properties([=[test_protocol2_stacking]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;763;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_protocol3_friction]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_protocol3_friction")
set_tests_properties([=[test_protocol3_friction]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;764;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_protocol4_ccd]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_protocol4_ccd")
set_tests_properties([=[test_protocol4_ccd]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;765;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_protocol5_determinism]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_protocol5_determinism")
set_tests_properties([=[test_protocol5_determinism]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;767;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_vulkan_memory]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_vulkan_memory")
set_tests_properties([=[test_vulkan_memory]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;772;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_dynamic_rendering]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_dynamic_rendering")
set_tests_properties([=[test_dynamic_rendering]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;773;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_moltenvk]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_moltenvk")
set_tests_properties([=[test_moltenvk]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;774;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
add_test([=[test_async_compute]=] "/Users/benjaminrussell/Desktop/Minecraft v2/build_phase1/test_async_compute")
set_tests_properties([=[test_async_compute]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;694;add_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;775;add_engine_test;/Users/benjaminrussell/Desktop/Minecraft v2/CMakeLists.txt;0;")
subdirs("src/engine/test")
subdirs("Vendor/Catch2")
